apiVersion: v1
kind: Service
metadata:
  name: webapp-argo-service
spec:
  type: LoadBalancer
  selector:
    app: webapp-argo
  ports:
    - protocol: TCP
      port: 80       # El puerto en el que el servicio será accesible
      targetPort: 5000 # El puerto en el que el contenedor está escuchando
