name: Deploy to Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t danielmesu25/webapp-argo:latest -f WebApp-Argo/Dockerfile WebApp-Argo
          docker push danielmesu25/webapp-argo:latest

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Create .kube directory
        run: mkdir -p ~/.kube

      - name: Set KUBECONFIG
        run: |
          echo "
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: ${{ secrets.CA_CERT_BASE64 }}
              server: https://127.0.0.1:59368
            name: minikube
          contexts:
          - context:
              cluster: minikube
              namespace: default
              user: minikube
            name: minikube
          current-context: minikube
          kind: Config
          preferences: {}
          users:
          - name: minikube
            user:
              client-certificate-data: ${{ secrets.CLIENT_CERT_BASE64 }}
              client-key-data: ${{ secrets.CLIENT_KEY_BASE64 }}
          " > ~/.kube/config

      - name: Debug KUBECONFIG
        run: cat ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml